base_url = "https://mibrah.im"
title = "Mohamed Alokl - Senior Software Engineer"
description = "Senior Software Engineer with extensive experience in API design, distributed architectures, data engineering, and AI-powered solutions. Based in Berlin, Germany."
compile_sass = true
minify_html = true
generate_feeds = false

[markdown]

[extra]
